#!/bin/bash

NC='\033[0m'
GREEN='\033[0;32m'

mkdir -p ~/bin

echo -e "${GREEN}Downloading...${NC}"
curl -sL https://raw.githubusercontent.com/gigante/sh/master/dk -o "$HOME/bin/dk"
curl -sL https://raw.githubusercontent.com/gigante/sh/master/px -o "$HOME/bin/px"
curl -sL https://raw.githubusercontent.com/gigante/sh/master/sam -o "$HOME/bin/sam"
chmod +x ~/bin/{dk,px,sam}
echo -e "${GREEN}Success${NC}"
